### ISSUE TITLE
Missing required data

### ISSUE THREAD

**Issue by bigdaddyky** [MediusEcho/ParticleHats#21]
[17:05:48 WARN]: [ParticleHats] Plugin ParticleHats v4.6.0 generated an exception while executing task 21807932
java.lang.IllegalArgumentException: missing required data class org.bukkit.Color
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:218) ~[guava-32.1.2-jre.jar:?]
        at org.bukkit.craftbukkit.CraftParticle.createParticleParam(CraftParticle.java:68) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at org.bukkit.craftbukkit.CraftWorld.spawnParticle(CraftWorld.java:2224) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at org.bukkit.craftbukkit.CraftWorld.spawnParticle(CraftWorld.java:2212) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at org.bukkit.craftbukkit.CraftWorld.spawnParticle(CraftWorld.java:2201) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at org.bukkit.craftbukkit.CraftWorld.spawnParticle(CraftWorld.java:2191) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at org.bukkit.craftbukkit.CraftWorld.spawnParticle(CraftWorld.java:2186) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at ParticleHats.jar/com.mediusecho.particlehats.particles.renderer.spigot.SpigotParticleRenderer.spawnParticle(SpigotParticleRenderer.java:42) ~[ParticleHats.jar:?]
        at ParticleHats.jar/com.mediusecho.particlehats.particles.effects.PixelEffect.displayParticle(PixelEffect.java:193) ~[ParticleHats.jar:?]
        at ParticleHats.jar/com.mediusecho.particlehats.particles.effects.PixelEffect.display(PixelEffect.java:174) ~[ParticleHats.jar:?]
        at ParticleHats.jar/com.mediusecho.particlehats.particles.Hat.displayType(Hat.java:539) ~[ParticleHats.jar:?]
        at ParticleHats.jar/com.mediusecho.particlehats.tasks.HatTask.displayHat(HatTask.java:203) ~[ParticleHats.jar:?]
        at ParticleHats.jar/com.mediusecho.particlehats.tasks.HatTask.checkHat(HatTask.java:122) ~[ParticleHats.jar:?]
        at ParticleHats.jar/com.mediusecho.particlehats.tasks.HatTask.run(HatTask.java:99) ~[ParticleHats.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.21.1.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by MediusEcho** [comment]
Which particle effect are you using when this error occurs?
