### ISSUE TITLE
Failed to load on 1.16.2 

### ISSUE THREAD

**Issue by slvlr** [MediusEcho/ParticleHats#3]
[11:58:00] [Server thread/ERROR]: Could not load 'plugins/ParticleHats.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.util.zip.ZipException: invalid LOC header (bad signature)
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:141) ~[patched_1.16.2.jar:git-Paper-174]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:397) ~[patched_1.16.2.jar:git-Paper-174]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:305) ~[patched_1.16.2.jar:git-Paper-174]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.loadPlugins(CraftServer.java:387) ~[patched_1.16.2.jar:git-Paper-174]
	at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:208) ~[patched_1.16.2.jar:git-Paper-174]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.2.jar:git-Paper-174]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-174]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
Caused by: java.util.zip.ZipException: invalid LOC header (bad signature)
	at java.util.zip.ZipFile.read(Native Method) ~[?:1.8.0_262]
	at java.util.zip.ZipFile.access$1400(ZipFile.java:60) ~[?:1.8.0_262]
	at java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:734) ~[?:1.8.0_262]
	at java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:434) ~[?:1.8.0_262]
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158) ~[?:1.8.0_262]
	at sun.misc.IOUtils.readNBytes(IOUtils.java:180) ~[?:1.8.0_262]
	at sun.misc.IOUtils.readAllBytes(IOUtils.java:116) ~[?:1.8.0_262]
	at java.util.jar.JarFile.getBytes(JarFile.java:426) ~[?:1.8.0_262]
	at java.util.jar.JarFile.getManifestFromReference(JarFile.java:193) ~[?:1.8.0_262]
	at java.util.jar.JarFile.getManifest(JarFile.java:180) ~[?:1.8.0_262]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:60) ~[patched_1.16.2.jar:git-Paper-174]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:137) ~[patched_1.16.2.jar:git-Paper-174]

**Comment by MediusEcho** [comment]
I can't recreate this issue on 1.16.2 Spigot or PaperMC. Did you download this .jar from the Spigot resource page?

**Comment by slvlr** [comment]
Yes I did @MediusEcho

**Comment by slvlr** [comment]
I have since gone back to the previous version and it works fine.
Do you want me to try re-downloading it?

**Comment by MediusEcho** [comment]
You could try re-downloading the .jar, it's possible something was corrupted. I downloaded the .jar from the resource page just to double check and i can't recreate that error.
